# Generated by Django 4.0 on 2024-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ImageElements',
            new_name='ImageElement',
        ),
    ]
